### ISSUE TITLE
Error when signing up

### ISSUE THREAD

**Issue by sanders41** [jackh404/ecoinsight#1]
When I try to sign up nothing happens. Checking the console there is  a 500 error `"module 'datetime' has no attribute 'utcnow'"`. I believe the issue is [here](https://github.com/jackh404/ecoinsight/blob/2183ca5a2ff2adc5e009b3c515ce1fc4a304a12d/api/index.py#L122). Because `datetime` is imported and not `from datetime import datetime` this line should uses `datetime.datetime`.

Additionally `utcnow` is depreciated so this should instead use `now` with a time zone of `utc`. https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow

**Comment by jackh404** [comment]
Thank you so much for checking this out! I really appreciate it!
________________________________
From: Paul Sanders ***@***.***>
Sent: Friday, March 22, 2024 8:57 PM
To: jackh404/ecoinsight ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jackh404/ecoinsight] Error when signing up (Issue #1)


When I try to sign up nothing happens. Checking the console there is a 500 error "module 'datetime' has no attribute 'utcnow'". I believe the issue is here<https://github.com/jackh404/ecoinsight/blob/2183ca5a2ff2adc5e009b3c515ce1fc4a304a12d/api/index.py#L122>. Because datetime is imported and not from datetime import datetime this line should uses datetime.datetime.

Additionally utcnow is depreciated so this should instead use now with a time zone of utc.
